{ name = "typescript-importer"
, dependencies =
  [ "aff"
  , "argonaut"
  , "arrays"
  , "console"
  , "control"
  , "debug"
  , "effect"
  , "either"
  , "foldable-traversable"
  , "functions"
  , "language-cst-parser"
  , "maybe"
  , "newtype"
  , "node-buffer"
  , "node-fs"
  , "node-fs-aff"
  , "node-path"
  , "node-process"
  , "nullable"
  , "optparse"
  , "ordered-collections"
  , "partial"
  , "prelude"
  , "psci-support"
  , "record"
  , "spec"
  , "strings"
  , "strings-extra"
  , "tidy-codegen"
  , "transformers"
  , "tuples"
  , "typelevel-prelude"
  , "typescript-utils"
  , "unfoldable"
  , "unsafe-coerce"
  , "untagged-union"
  , "uuid"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
, license = "MIT-0"
, repository =
    "https://github.com/sigma-andex/purescript-typescript-importer.git"
}
